# Generated by Django 6.0.6 on 2026-07-02 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.ForeignKey(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', on_delete=django.db.models.deletion.CASCADE, to='tasks.priority'),
        ),
    ]
